BrightspaceUI/visual-diff

.travis.yml, README.md, package.json
This PR adds required stuff for deploying to NPM with our scope `@brightspace-ui`.
Note: scoped packages are private by default.  In order to publish as public, we add to `package.json`:
```
"publishConfig": {
"access": "public"
},
```
FYI: We cannot have private packages in our org since it's free.  As such, trying to publish without this config will result in publish error.
=> Update for publishing to npm.

bin/commit-goldens.js, package.json
The PR build status does not get updated (e.g., https://github.com/BrightspaceHypermediaComponents/activities/pull/433) if the latest commit has `[skip ci]` so I think we should remove it. Given that we want to rerun the build anyways (and manually do so) to make sure it passes after the goldens get updated, this seems fine to me. I am open to other suggestions though.
=> Remove [skip ci] from commit message when goldens committed

file-helper.js, package.json
This is an attempt to avoid `Error: Unexpected end of input` when using pngjs.
>       Uncaught Error: Unexpected end of input
>       at module.exports.ChunkStream._end (node_modules/pngjs/lib/chunkstream.js:100:7)
>       at module.exports.ChunkStream._process (node_modules/pngjs/lib/chunkstream.js:203:12)
>       at module.exports.ChunkStream.end (node_modules/pngjs/lib/chunkstream.js:90:10)
>       at module.exports.ParserAsync._finished (node_modules/pngjs/lib/parser-async.js:143:8)
>       at module.exports.Parser._parseIEND (node_modules/pngjs/lib/parser.js:295:10)
>       at module.exports.ChunkStream._processRead (node_modules/pngjs/lib/chunkstream.js:174:13)
>       at module.exports.ChunkStream._process (node_modules/pngjs/lib/chunkstream.js:193:14)
>       at …
=> Update to use PNG.sync.read.

package.json, visual-diff.js
I need to wait for `intl-messageformat` to be upgraded in [localize-behavior](https://github.com/BrightspaceUI/localize-behavior/pull/30) and [core](https://github.com/BrightspaceUI/core/pull/339), but wanted to get this up.
This switches visual-diff over to use `es-dev-server` instead of `polyserve`. It was mostly a clean switch, and the directory structure of where everything is and goes is simplified (no more `components/component-name`).
=> switching from polyserve to es-dev-server

README.md, package.json, test/test.visual-diff.js, visual-diff.js
* add default `setViewport` (800x800 seems to be most common) to `createPage` so that consumers don't need to specify
* add updated golden count to log so consumers have more confidence that goldens were updated as they expected.
=> default viewport and updated golden count

visual-diff.js
The deletion of orphaned goldens doesn't work properly if different test files use the same name key.    Since this used to be a requirement, most places should already be setup this way and we'll just add that requirement back.
=> feat: check for duplicate name keys

s3-helper.js
`RoleSessionName` has a character limit of 64.  We don't know how long our repo names will be, so we'll add that information as tags instead, and keep the `RoleSessionName` a fixed length.
=> fix: Add tags for org and repo instead of combining them in RoleSessionName

README.md
This PR expands on the examples for visual-diff in order to give consumers more direction in terms of writing tests, including things like media-queries, animations, async behaviors, and rtl.  I don't want to spend too much time on this, since this is subject to change shortly assuming I can inject fixtures into a page, thereby simplifying some of the setup.
=> First stab at flushing out some additional examples for visual-diff.

s3-helper.js
Tried running visual-diff locally but because `s3-helper.js` is included in `file-helper.js`, even though it's not actually used it still blows up because the `GITHUB_REPOSITORY` environment variable is missing.
So I switched things around a bit to defer access that variable until it's actually needed.
=> fix: defer referencing env variables to allow local runs

s3-helper.js
In https://github.com/BrightspaceUI/visual-diff/pull/33, I changed `repo` from being owner + repo to just repo.  This affected the target path below (https://github.com/BrightspaceUI/visual-diff/pull/33/files#diff-268e65a4270639d14f1c5d869fa67f1ce01beecb711faa1b87eddccd72fc5359R47), so our reports started being saved at `/screenshots/core` instead of `screenshots/BrightspaceUI/core`.  Not a huge deal, but we could theoretically have a repo of the same name in different orgs and that would cause weirdness, plus it helps to organize things.
=> fix: S3 bucket path should include the owner and repo

visual-diff.js
I find in long reports it can be hard to tell quickly which visual-diff tests failed because sometimes there's no diff image (if the images are different sizes, or the test is new and there is no golden) or things may be scrolled offscreen for long diffs.  Thoughts on adding a button to quickly hide the ones that are all good?
Unchecked (default):
Checked:
=> feat: Add a "Show Only Failed Tests" button to the reports

README.md, visual-diff.js
In native ESM, `__dirname` is no longer supported. Instead, `import.meta.url` provides the URL to the current file. Outside of a web context, that URL will be in the form `file://path/to/file.js`.
This change allows visual-diff to handle both a normal directory path (from `__dirname`) OR `import.meta.url` and continue to work the same in either case.
This will allow us to start converting consumers over to pass `import.meta.url` before we switch visual-diff to be full ESM, allowing for a transition period. Then once visual-diff is full ESM, we can drop support for `__dirname` as part of its major release.
=> fix: support both "__dirname" and "import.meta.url" from ESM sources

visual-diff.js
Noticed in core that after you run visual diffs locally, ESLint complains about the generated `report.html` files. Ideally ESLint would ignore them, but also ideally they pass linting!
=> fix: use arrow functions to pass linting

.github/dependabot.yml, README.md, file-helper.js, helpers/createPage.js, helpers/disableAnimations.js, helpers/getRect.js, helpers/index.js, helpers/oneEvent.js, helpers/resetFocus.js, index.js, package.json, s3-helper.js, test/test.visual-diff.js, visual-diff.js
This updates visual-diff to be a native ES module. This will be a BREAKING CHANGE.
I was a little ambitious, and updated it to use `@web/dev-server` as well, which _seems_ to be working. ~The visual-diff CI is going to fail until we update that action to use Mocha version 9.~ Actually no it won't, since it's passing the `--require esm` flag.
=> Switch to native ESM

package.json
This reverts commit 21ca96dac4d776a9842ddca2eeee11dbd83f0310.
We treat mocha version bumps as a breaking change for visual-diff, so reverting this and then I'll re-apply with a major bump.
=> Revert "chore(deps-dev): bump mocha from 9.2.2 to 10.0.0 (#66)"

package.json, visual-diff.js
The other step to this is adding `--retries=${{ inputs.RETRIES }}` to this line https://github.com/BrightspaceUI/actions/blob/main/visual-diff/action.yml#L52 and adding `RETRIES` to the file (which I was thinking of defaulting to either 1 or 2?)
When adding `--retries` to the mocha command, it by default retries X number of times. The change here is so that when retrying, the result isn't added to results X number of times, only the last time.
=> Support retrying visual diff tests

visual-diff.js
[US147269](https://rally1.rallydev.com/#/?detail=/userstory/675673548423&fdp=true)
This PR updates visual-diff to ensure that a high return code is returned if there are orphaned goldens but no other golden updates. Without this, a PR to remove the goldens will not be created because there are no other failures.
=> Update visual-diff to return a high return code if there are orphaned goldens.

README.md, helpers/focus.js, index.js
As we add more `:focus-visible`-specific styles that don't show up during `:focus`, we need a consistent way to trigger them. This mirrors the [helper in core](https://github.com/BrightspaceUI/core/blob/main/tools/web-test-runner-helpers.js#L3), which fires a keyboard event to put the browser into "keyboard mode" and then focuses on the element.
This would replace all uses of `forceFocusVisible` in our visual-diff tests.
This leaves `focus()` in kind-of a weird place... it's essentially `focusWithMouse` at this point... not sure what to do with it.
=> feat: add focusWithKeyboard

README.md, helpers/focus.js
I'm running into a few cases that need to use `focusWithKeyboard`, but they need to focus on an element inside a web component's shadow root -- not just in the root document.
This allows the provided selector to optionally be an array of selectors. When that's the case, the elements' shadow roots will be queried for each entry.
=> feat: allow nested selectors

helpers/focus.js
Forgot to pass the `selectors` parameter to `focusWithMouse`. 🤦
=> fix: pass parameter

helpers/focus.js
When we Tab to enable keyboard mode, it's causing text in inputs to get selected. That isn't quite what we intended here. Using "Cancel" instead seems to also work.
=> fix: use Cancel instead of Tab to avoid selecting text
